// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt2S2kTYNyuzeQQ7Tl3o6Ace03UmTDKAU',
    appId: '1:74451662375:web:9bfdb5812726837b6e8002',
    messagingSenderId: '74451662375',
    projectId: 'android-app-14bfe',
    authDomain: 'android-app-14bfe.firebaseapp.com',
    storageBucket: 'android-app-14bfe.firebasestorage.app',
    measurementId: 'G-TY846ZBCW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9UMkgOcKNWWQ1TdditsAy6I1iJDrvbw',
    appId: '1:74451662375:android:301f3d96c538a6296e8002',
    messagingSenderId: '74451662375',
    projectId: 'android-app-14bfe',
    storageBucket: 'android-app-14bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfsnbcA2WS8W_wvP6bCJ3D2zWBb0IvhvE',
    appId: '1:74451662375:ios:c4cb1d55200f09f06e8002',
    messagingSenderId: '74451662375',
    projectId: 'android-app-14bfe',
    storageBucket: 'android-app-14bfe.firebasestorage.app',
    iosBundleId: 'com.example.deledata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfsnbcA2WS8W_wvP6bCJ3D2zWBb0IvhvE',
    appId: '1:74451662375:ios:c4cb1d55200f09f06e8002',
    messagingSenderId: '74451662375',
    projectId: 'android-app-14bfe',
    storageBucket: 'android-app-14bfe.firebasestorage.app',
    iosBundleId: 'com.example.deledata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt2S2kTYNyuzeQQ7Tl3o6Ace03UmTDKAU',
    appId: '1:74451662375:web:2fb6136c381c9f6c6e8002',
    messagingSenderId: '74451662375',
    projectId: 'android-app-14bfe',
    authDomain: 'android-app-14bfe.firebaseapp.com',
    storageBucket: 'android-app-14bfe.firebasestorage.app',
    measurementId: 'G-1E6EFE9SNE',
  );
}
